################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    - &CaseOrdererOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: CaseOrdererOrg

        # ID to load the MSP definition as
        ID: CaseOrdererMSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/ordererOrganizations/justice.com/msp

        # Policies for reading, writing, configuration
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('CaseOrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('CaseOrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('CaseOrdererMSP.admin')"

    - &FBIOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: FBIOrgMSP

        # ID to load the MSP definition as
        ID: FBIOrgMSP

        MSPDir: crypto-config/peerOrganizations/fbi.justice.com/msp

        # Policies for reading, writing, configuration
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('FBIOrgMSP.admin', 'FBIOrgMSP.peer', 'FBIOrgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('FBIOrgMSP.admin', 'FBIOrgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('FBIOrgMSP.admin')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.fbi.justice.com
              Port: 7051

    - &NYPDOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: NYPDOrgMSP

        # ID to load the MSP definition as
        ID: NYPDOrgMSP

        MSPDir: crypto-config/peerOrganizations/nypd.justice.com/msp

        # Policies for reading, writing, configuration
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('NYPDOrgMSP.admin', 'NYPDOrgMSP.peer', 'NYPDOrgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('NYPDOrgMSP.admin', 'NYPDOrgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('NYPDOrgMSP.admin')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.nypd.justice.com
              Port: 7051

    - &NJSPOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: NJSPOrgMSP

        # ID to load the MSP definition as
        ID: NJSPOrgMSP

        MSPDir: crypto-config/peerOrganizations/njsp.justice.com/msp

        # Policies for reading, writing, configuration
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('NJSPOrgMSP.admin', 'NJSPOrgMSP.peer', 'NJSPOrgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('NJSPOrgMSP.admin', 'NJSPOrgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('NJSPOrgMSP.admin')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.njsp.justice.com
              Port: 7051

    - &JudiciaryOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: JudiciaryOrgMSP

        # ID to load the MSP definition as
        ID: JudiciaryOrgMSP

        MSPDir: crypto-config/peerOrganizations/judiciary.justice.com/msp

        # Policies for reading, writing, configuration
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('JudiciaryOrgMSP.admin', 'JudiciaryOrgMSP.peer', 'JudiciaryOrgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('JudiciaryOrgMSP.admin', 'JudiciaryOrgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('JudiciaryOrgMSP.admin')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.judiciary.justice.com
              Port: 7051

################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: solo

    Addresses:
        - orderer.justice.com:7050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - 127.0.0.1:9092

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

    # Policies defines the set of policies at this level of the config tree
    # For Orderer policies, their canonical path is
    #   /Channel/Orderer/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "ANY Admins"
        # BlockValidation specifies what signatures must be included in the block
        # from the orderer for the peer to validate it.
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:

    # Policies defines the set of policies at this level of the config tree
    # For Application policies, their canonical path is
    #   /Channel/Application/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "ANY Admins"

################################################################################
#
#   CHANNEL
#
#   This section defines the values to encode into a config transaction or
#   genesis block for channel related parameters.
#
################################################################################
Channel: &ChannelDefaults
    # Policies defines the set of policies at this level of the config tree
    # For Channel policies, their canonical path is
    #   /Channel/<PolicyName>
    Policies:
        # Who may invoke the 'Deliver' API
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        # Who may invoke the 'Broadcast' API
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        # By default, who may modify elements at this config level
        Admins:
            Type: ImplicitMeta
            Rule: "ANY Admins"

