################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    - &CaseOrdererOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: CaseOrdererOrg

        # ID to load the MSP definition as
        ID: CaseOrdererMSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/ordererOrganizations/justice.com/msp

        # Policies for reading, writing, configuration
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('CaseOrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('CaseOrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('CaseOrdererMSP.admin')"

    - &FBIOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: FBIOrgMSP

        # ID to load the MSP definition as
        ID: FBIOrgMSP

        MSPDir: crypto-config/peerOrganizations/fbi.justice.com/msp

        # Policies for reading, writing, configuration
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('FBIOrgMSP.admin', 'FBIOrgMSP.peer', 'FBIOrgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('FBIOrgMSP.admin', 'FBIOrgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('FBIOrgMSP.admin')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.fbi.justice.com
              Port: 7051

    - &NYPDOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: NYPDOrgMSP

        # ID to load the MSP definition as
        ID: NYPDOrgMSP

        MSPDir: crypto-config/peerOrganizations/nypd.justice.com/msp

        # Policies for reading, writing, configuration
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('NYPDOrgMSP.admin', 'NYPDOrgMSP.peer', 'NYPDOrgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('NYPDOrgMSP.admin', 'NYPDOrgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('NYPDOrgMSP.admin')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.nypd.justice.com
              Port: 7051

